version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Retrieving API URL from SSM Parameter Store...
      - NEXT_PUBLIC_API_URL=$(aws ssm get-parameter --name "$SSM_PARAMETER_NAME" --with-decryption --query "Parameter.Value" --output text)
      - echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
      - echo ".env file updated with API URL"
      - echo "Contents of .env file:"
      - cat .env
  build:
    commands:
      - yarn run build

artifacts:
  files:
    - "**/*"
  base-directory: ./
