version: 0.2

phases:
  install:
    commands:
      - n 20.10.0
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - yarn run build


artifacts:
  files:
      - "**/*"
  base-directory: ./